[ { created_at: 'Tue Mar 20 23:03:02 +0000 2018',
    id: 976232678902157300,
    id_str: '976232678902157312',
    text: 'what would you do for a Klondike bar',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 976070743195865100,
       id_str: '976070743195865090',
       name: 'Kohl B Eisenschmidt',
       screen_name: 'KohlBEisen',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 0,
       friends_count: 0,
       listed_count: 0,
       created_at: 'Tue Mar 20 12:19:34 +0000 2018',
       favourites_count: 0,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 23,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: true,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' } ]